platform:
  - Win32

os: Visual Studio 2015

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.8"
  PYTHON_ARCH: "32"
  CONAN_USERNAME: "TimSimpson"

install:
  - echo * * * Setting up Conan  * * *
  - set PATH=%PATH%;%PYTHON%\Scripts\
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
  - echo * * * Downloading Macaroni * * *
  - mkdir C:\Libraries\Macaroni
  - ps: Start-FileDownload 'http://border-town.com/macaroni/downloads/macaroni-0.4.3-windows.zip' -FileName 'C:\Libraries\Macaroni\macaroni.zip'
  - echo unzipping
  - 7z x C:\Libraries\Macaroni\macaroni.zip  -oC:\Libraries\Macaroni\ -r
  - SET PATH=%PATH%;C:\Libraries\Macaroni

build_script:
  - cmd: >-

      SET PATH=%PATH%;%PYTHON%\Scripts\;C:\Libraries\Macaroni

      cd %APPVEYOR_BUILD_FOLDER%

      mkdir build

      cd build

      conan install .. --build

      conan build ..


artifacts:
  - path: build/bin/cowsay.exe
    name: cowsay.exe
